### ISSUE TITLE
Error during Chain Code Instantiate 

### ISSUE THREAD

**Issue by rupeshtr78** [feitnomore/hyperledger-fabric-kubernetes#5]
Chaincode Instantiate fails with failed to invoke chaincode name:"lscc" , error: timeout expired while starting chaincode rtrcc:1.0 for transaction.

I made a simplified model with one org one peer and one orderer.I have 2 k8s nodes
I am able to launch orderer and peer pods , create channel , fetch blocks , install chaincode.
But above error comes up during chain code instantiate.
Chaincode Image gets created in one of the nodes.
I can see docker container build on one of my nodes using docker ps -a but it gets removed quickly.
Instantiate hangs for about 10 minutes or more before throeing this error in CLI

Error: could not assemble transaction, err proposal response was not successful, error code 500, 
msg timeout expired while starting chaincode rtrcc:1.0 for transaction

**Peers Logs**
stopInternal -> DEBU 2ecf kill container result id=nid1-peer0-org1-rtrcc-1.0 error="Container not running: nid1-peer0-org1-rtrcc-1.0"
[dockercontroller] stopInternal -> DEBU 2ed0 removing container id=nid1-peer0-org1-rtrcc-1.0
[dockercontroller] stopInternal -> DEBU 2ed1 remove container result id=nid1-peer0-org1-rtrcc-1.0 error=null
[container] unlockContainer -> DEBU 2ed2 container lock deleted(rtrcc-1.0)
[chaincode] Launch -> DEBU 2ed3 launch complete
[chaincode] Deregister -> DEBU 2ed4 deregister handler: rtrcc:1.0
[endorser] callChaincode -> INFO 2ed5 [rtrchannel01][647de024] Exit chaincode: name:"lscc"  (537845ms)
[endorser] SimulateProposal -> ERRO 2ed6 [rtrchannel01][647de024] failed to invoke chaincode name:"lscc" , error: timeout expired while starting chaincode rtrcc:1.0 for transaction

Looks like the chain code containers is not able to reach k8s pods.

**Comment by feitnomore** [comment]
I don't know what chaincode is lscc. Its strange, because the documentation as it is works, I've got multiple feedbacks that everything is working fine. If you changed the topology, probably you forgot to set something. The communications between the containers is done through volume /var/run/docker.sock. Make sure you've got that volume working fine. Also, make sure the policies when you are instantiating the chaincode are OK. As explained the model is for 4 orgs with 2 peers each, which means, at instantiate moment we're making sure we have at least 1 peer for each org is endorsing the transaction. You might wanna check that up too.

**Comment by rupeshtr78** [comment]
Thanks for the pointer to volume /var/run/docker.sock.That lead me to this
git https://github.com/IBM/blockchain-network-on-kubernetes.
Looks like it was due to the Kubernetes Server versio I deployed.Anyways
this lead me to use docker Dind as the pod/container for chaincode and its
working.
Thanks for the detailed post of github on this topic.

Rupesh
